config/routes.rb
Rails.application.routes.draw do
  get 'votings/index'
  root to: 'pages#home'

  get 'infocamara', to: "pages#infocamara"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :councillors, only: [:index, :show]
  resources :projects, only: [:index, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  belongs_to :councillor
end

app/models/authorship.rb
class Authorship < ApplicationRecord
  belongs_to :project
  belongs_to :councillor
  validates :project, uniqueness: { scope: :councillor }
end

app/models/autorship.rb
class Autorship < ApplicationRecord
  belongs_to :project
  belongs_to :councillor
  validates :project, uniqueness: { scope: :councillor }
end

app/models/councillor.rb
class Councillor < ApplicationRecord
  has_many :votings
  has_many :attendances
  has_many :authorships
  has_many :projects, through: :authorships

  def self.councillors_project_status(councillor_id)
  sql = "
    SELECT * FROM projects p
    JOIN authorships a ON a.project_id = p.id
    JOIN councillors c ON c.id = a.councillor_id
    WHERE councillor_id = \'#{councillor_id}\' "

  query = ActiveRecord::Base.connection.execute(sql)

  return query

  # .group_by { |c| c['ano'] }.map do |councillor_array|
  #   councillor_array[1].map do |result|
  #     [councillor_array[0], result['status']]
    # end
  # end

  end

end

app/models/presence.rb
class Presence < ApplicationRecord
  belongs_to :councillor
  belongs_to :session
  validates :session, uniqueness: { scope: :councillor }
end

app/models/project.rb
class Project < ApplicationRecord
  has_many :votings
  has_many :authorships
  has_many :councillors, through: :authorships

  def self.councillors_names(ano, tipo)
    sql = "
      SELECT c.* FROM projects p
      JOIN authorships a ON a.project_id = p.id
      JOIN councillors c ON c.id = a.councillor_id
      WHERE tipo = \'#{tipo}\' AND ano = #{ano}
    "

    query = ActiveRecord::Base.connection.execute(sql)

    query.group_by { |c| c['name'] }.map do |councillor_array|
      #
      # councillor_array[0] its the name of the councillor
      # councillor_array[1] its his projects tipo
      #
      [
        councillor_array[0], councillor_array[1].count
      ]
    end


  end
end

app/models/voting.rb
class Voting < ApplicationRecord
  belongs_to :project

# Votings with date range
  def self.session_grouped(date_range = {})
    date_range = {
      start_date: order(:vote_date).pluck(:vote_date).first,
      end_date: order(:vote_date).pluck(:vote_date).last
    } if date_range.empty?

    where("vote_date > ? AND vote_date < ?", date_range[:start_date], date_range[:end_date])
      .group(:sessao).count
  end

# Votings with date range
  def self.grouped_by_year(date_range = {})
    date_range = {
      start_date: order(:vote_date).pluck(:vote_date).first,
      end_date: order(:vote_date).pluck(:vote_date).last
    } if date_range.empty?

    where("vote_date > ? AND vote_date < ?", date_range[:start_date], date_range[:end_date])
      .group_by_month(:vote_date, format: "%b %Y").count
  end

# Votings by project_id
  def self.project_grouped
    group(:project_id).count
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/councillors_controller.rb
class CouncillorsController < ApplicationController
  require 'open-uri'
  require 'nokogiri'

  def index
    @councillors = Councillor.joins(:votings).where("vote_date > ?", Date.parse("01 Jan 2017")).uniq
    general_total_days = Attendance.where("att_date > ?", Date.parse("01 Jan 2017")).count.to_f
    general_present_days = Attendance.where("att_date > ? AND present = ?", Date.parse("01 Jan 2017"), true).count.to_f
    @general_presence = (general_present_days / general_total_days * 100).floor(2)
    @party_attendances = count_attendances
    @parties_projects2016 = count_projects(2016)
    @parties_projects2017 = count_projects(2017)
  end

  def show
    @councillors = index
    @councillor = Councillor.find(params[:id])
    @total_days = @councillor.attendances.where("att_date > ?", Date.parse("01 Jan 2017")).count.to_f
    @present_days = @councillor.attendances.where("att_date > ? AND present = ?", Date.parse("01 Jan 2017"), true).count.to_f
    @presence = (@present_days / @total_days * 100).floor(2)
    @ranking_tipos = rank_types(@councillor)
    @tipo_list_show = @councillor_projects.map { |p|
      p[:tipo]
    }.uniq
    @projects = Project.joins(:authorships).where(authorships: {councillor: @councillor} )
    @status_list = ["Em Tramitação", "Vetado", "Aprovado", "Promulgado", "Encerrado por Ilegalidade", "Retirado pelo autor"]
  end


  private

  def count_attendances
    hash = {}
    attendances = Attendance.where("att_date > ?", Date.parse("01 Jan 2017"))
    att_parties = attendances.map { |att| att[:party] }.uniq
    att_parties.each do |partido|
      hash[partido] = (attendances.where(party: partido, present: true).count.to_f /
                        attendances.where(party: partido).count.to_f * 100).floor(2)
    end
    return hash
  end

  def rank_types(councillor)
    @councillor_projects = Project.where.not(tipo: "SUB").joins(:authorships).where(authorships: { councillor: councillor })
  end

  def count_projects(year)
    parties = Attendance.where("att_date > ?", Date.parse("01 Jan 2017")).map { |att| att[:party] }.uniq
    hash = {}
    parties.each do |partido|
      hash[partido] = Project.where("ano > ?", year).joins(:councillors).where(councillors: { party: partido }).count
    end
    return hash
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def infocamara
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
    @projects = Project.all
    @parties_projects2016 = count_projects(2016)
    @parties_projects2017 = count_projects(2017)
    @project_list = ["PL", "PDL", "RDS", "IND", "SUB"]
    @status_list = ["Em Tramitação", "Vetado", "Aprovado", "Promulgado", "Encerrado por Ilegalidade", "Retirado pelo autor"]
  end

  def show
    @project = Project.find(params[:id])
  end

  private

  def count_projects(year)
    parties = Attendance.where("att_date > ?", Date.parse("01 Jan 2017")).map { |att| att[:party] }.uniq
    hash = {}
    parties.each do |partido|
      hash[partido] = Project.where("ano > ?", year).joins(:councillors).where(councillors: { party: partido }).count
    end
    return hash
  end
end

app/controllers/votings_controller.rb
class VotingsController < ApplicationController
  def index
    # query = params[:query]

    @votings = Voting.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/views/councillors/index.html.erb
<div class="section" id="attendance-chart">
  <div class="section-presentation">
    <h3>PRESENÇA</h3>
  </div>
  <div class="row col-xs-12">
    <div class="project-info col-xs-4">
      <div class="icon">
        <i class="fas fa-user-check"></i>
      </div>
      <br><br>
      <div class="info-texto">
        <p>A base de cálculo da presença dos vereadores foi obtida a partir de um arquivo como <%= link_to 'este', 'https://splegispdarmazenamento.blob.core.windows.net/containersip/PRESENCAS_2018.xml', target:"_blank" %>.<br>Nele, podemos ver se cada candidato compareceu ou não à sessão de um determinado dia. A partir daí, através de um cálculo simples, consideramos qualquer outro status diferente de <em>Presente</em>, como um não-comparecimento à sessão.<br><br><em>Mas por que isso é importante?</em><br>O não comparecimento às sessões pode causar o seu cancelamento por falta de participantes e, desta maneira, a Câmara de São Paulo deixa de apresentar, discutir e votar projetos que possam ser importantes para a cidade.</p>
      </div>
    </div>

    <div class="project-info col-xs-4">
      <div class="icon">
        <i class="fas fa-users"></i>
      </div>
      <br><br>
      <div class="info-texto">
        <p>A barra abaixo representa a média de presença de todos os vereadores do mandato corrente, ou seja, desde o início de 2017:</p>
      </div>
      <div class="progress">
        <div class="progress-bar" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width:<%= @general_presence %>%;">
          <%= @general_presence %>%
        </div>
      </div>
      <br><br>
      <div class="info-texto">
        <p>Caso tenha interesse em acompanhar a presença individual de um vereador, selecione seu nome abaixo:</p>
      </div>
        <form>
          <div class="form-group">
            <label for="exampleFormControlSelect1">Escolha um vereador</label>
            <select class="form-control" id="exampleFormControlSelect1">
              <% @councillors.each do |councillor| %>
                <option data-id=<%= "#{councillor.id}" %>>
                  <%= link_to councillors_path(councillor) do %>
                    <%= councillor.name %>
                  <% end %>
                </option>
              <% end %>
            </select>
          </div>
        </form>
    </div>

    <div class="project-info col-xs-4">
      <div class="icon">
        <i class="far fa-flag"></i>
      </div>
      <br><br>
      <div class="info-texto">
        <p>Abaixo, temos a média de presença de cada partido desde o início de 2017:</p>
      </div>
      <div class="scroll-wrapper">
        <div class="col-xs-12">
          <% @party_attendances.each do |party| %>
            <div class="card align-center">
              <%= party[0] %>
            </div>
            <div class="card align-center">
              <div class="progress">
                <div class="progress-bar" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width:<%= party[1] %>%;">
                  <%= party[1] %>%
                </div>
              </div>
            </div>
          <% end %>
        </div>
      </div> <!-- scroll-wrapper -->
    </div>

  </div> <!-- row -->
</div> <!-- section -->




<div class="section" id="projetos-partido">
  <div class="section-presentation">
    <h3>QUANTIDADE DE PROJETOS POR PARTIDO</h3>
  </div>
  <br>
  <div class="row col-xs-12">
    <div class="project-info col-xs-4 col-xs-offset-1">
      <div class="icon">
        <i class="far fa-file-alt"></i>
      </div>
      <br><br>
      <div class="info-texto">
        <p>A base de cálculo da quantidade de projetos por partido foi obtida a partir de um arquivo como <%= link_to 'este', 'http://splegisws.camara.sp.gov.br/ws/ws2.asmx/ProjetosPorAnoJSON?ano=2018', target:"_blank" %>.<br>Nele é possível visualizar individualmente projetos de 2018 e de que <%= link_to 'tipo', '/projects', target:"_blank" %> são. <br>
        A tabela abaixo mostra a composição de partidos na Câmara de São Paulo e a partir dessa informação é possível cruzar informações do gráfico com a representatividade do partido.</p>
      </div>

      <div>
        <%= render 'components/table' %>
      </div>
    </div>
    <div class="project-info col-xs-4">
      <div class="chart-box">
        <div class="chart-card align-center" style="width: 600px; height: 400px;">
          <%= column_chart @parties_projects2017, thousands: ".", width: "580px", height: "300px", xtitle: "Partido",ytitle: "Quantidade"  %>
          <br>
          <p>  Projetos lançados por partidos em 2018</p>
        </div>
      </div>
      <div class="chart-box">
        <div class="chart-card align-center" style="width: 600px; height: 400px">
          <%= column_chart @parties_projects2016, thousands: ".", width: "580px", height: "300px", xtitle: "Partido", ytitle: "Quantidade" %>
          <br>
          <p>  Projetos lançados por partidos em 2017</p>
        </div>
      </div>
    </div>
  </div> <!-- row-camara -->
</div> <!-- section -->

app/views/councillors/show.html.erb
<div class="container">

  <div class="councillor-title">
    <h1><%= @councillor.name.split(" ").map { |n| n.capitalize }.join(" ") %> - <%= @councillor.party %></h1>
  </div>

  <div class="councillor-info">
    <div class="card" id="profile-info">
      <div id="councillor-photo">
        <% if @councillor.photo %>
          <%= image_tag(@councillor.photo) %>
        <% end %>
        <% if @councillor.name %>
          <h5><strong>Nome:</strong> <%= @councillor.name.split(" ").map { |n| n.capitalize }.join(" ") %></h5>
        <% end %>
        <% if @councillor.party %>
          <h6><strong>Partido:</strong> <%= @councillor.party %></h6>
        <% end %>
      </div>
      <br>
      <div class="councillor-presence">
        <h6>Presença nas sessões:</h6>
        <div class="progress-bar" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width:<%= @presence %>%;">
            <%= @presence %>%
        </div>
      </div>
    </div>

    <div class="charts">
      <div class="row">
        <div class="card" id="more-about">
         <h5>Status de projetos apresentados:</h5>
        <div class="card-content">
          <%= line_chart @status_list.map { |stat|
      {name: stat, data: @projects.where(status: stat).group(:ano).count }
        }, height: "300px", width:"600px", thousands: ".", discrete: true, legend: "bottom", xtitle: "Ano", ytitle:"Quantidade" %>
        </div> <!-- card-content -->
      </div> <!-- card -->
          <h5>Tipos de projetos apresentados:</h5>
        <div class="col-xs-12">
        <div class="chart-project-type-show">
          <div class="chart-content">
            <%= line_chart @tipo_list_show.map { |tipo|
              { name: tipo, data: @councillor_projects.where(tipo: tipo).group(:ano).count
              } },legend: "bottom", width: "600px", discrete: true, xtitle: "Ano", ytitle:"Quantidade" %>
          </div> <!-- card-content -->
        </div>
        <div class="project-labels">
          <div class="texto-explicativo">
            <p>Segue abaixo a lista de siglas utilizadas para denominação de cada tipo de projeto. A lista completa pode ser encontrada neste <%= link_to 'link', 'http://splegisws.camara.sp.gov.br/ws/ws2.asmx/TiposDeMateria', target: "_blank" %>.</p>
          </div>
          <div class="scroll-wrapper" id="project-labels">
            <%= render 'components/tipos_de_projeto' %>
          </div>
        </div>
        </div>
      </div>


    </div>
  </div> <!-- councillor-info -->

</div> <!-- container -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>DE-CODECITY - Decifrando a Câmara de São Paulo</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= javascript_include_tag 'application' %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
    <%= favicon_link_tag %>
  </head>
  <body>
    <%= render 'components/navbar' %>
    <%= yield %>
    <%= render 'components/footer' %>
    <%= javascript_pack_tag 'application' %>
    <%= javascript_include_tag "https://www.gstatic.com/charts/loader.js" %>
  </body>
</html>

app/views/pages/home.html.erb
<div id="banner">
</div>

<div class="section">
  <div class="row-camara col-xs-12" id="surgimento">
    <br>
    <a id="sobre-section"><h3>COMO SURGIU O PROJETO?</h3></a>
    <div class="project">
      <div class="project-info col-xs-3">
        <div class="icon">
          <i class="far fa-lightbulb"></i>
        </div>
        <br>
        <br>
        <div class="info-texto">
          <p> Você se lembra em quem votou para vereador na última eleição? Sabe se essa pessoa foi eleita? E, em caso positivo, como está trabalhando na Câmara de Vereadores? Quais veículos de informação você utiliza para saber sobre isso? Será que eles dão a atenção devida para essas informações?</p>
        </div>
      </div>
      <div class="project-info col-xs-3">
        <div class="icon">
          <i class="fa fa-shopping-basket"></i>
        </div>
        <br>
        <br>
        <div class="info-texto">
          <p> A lei de <%= link_to 'Dados Abertos', 'http://dados.gov.br/noticia/primeira-lei-de-acesso-no-mundo-que-preve-dados-abertos', target:"_blank" %> disponibiliza uma base de dados eletrônica, para que qualquer cidadão possa utilizar e tirar conclusões sobre o funcionamento de algumas instituições públicas. Legal! Mas você já visualizou como esses dados são <%= link_to 'disponibilizados', 'http://www.saopaulo.sp.leg.br/wp-content/uploads/dados_abertos/vereador/vereador.txt' %>? Achou confuso? Nós também!</p>
        </div>
      </div>
      <div class="project-info col-xs-3">
        <div class="icon">
          <i class="fa fa-cogs"></i>
        </div>
        <br>
        <br>
        <div class="info-texto">
          <p>Enquanto ainda não temos tecnologias como as do seriado <em>Black Mirror</em> em nossos olhos para tirarmos conclusões a respeito dessas APIs, resolvemos criar o Projeto Vérteres. Nele, damos uma "arrumadinha" nesses dados e disponibilizamos de uma maneira mais fácil de ser digerida por nós, seres humanos. </p>
        </div>
      </div>
    </div>
  </div>

<div class="section" id="camara">

  <div class="section-presentation">
    <h3>ALGUNS FATOS SOBRE A CÂMARA DE SÃO PAULO</h3>
  </div>
  <br>
  <div class="row-camara col-xs-12">
    <div class="info-box col-xs-3">
      <div class="number">55</div>
      <div class="number-desc">é o número de vereadores eleitos.</div>
    </div>
    <div class="info-box col-xs-3">
      <div class="number">4 anos</div>
      <div class="number-desc">é a duração de seu mandato, sem limite para reeleição.</div>
    </div>
    <div class="info-box col-xs-3">
      <div class="number">150%</div>
      <div class="number-desc">é o número de vagas disponíveis no município. Esta é a quantidade de vereadores que cada partido pode lançar.</div>
    </div>
    <div class="box-sem-borda col-xs-3">
      <div class="number" style="font-size: 36px;">R$ 156 mil/mês</div>
      <div class="number-desc"><br>é a verba de gabinete por vereador, que é o dinheiro destinado à contratação de assessores.</div>
    </div>
  </div>
  <br><br><br>
  <br><br><br>
  <br><br><br>
  <div class="infocamara-button col-xs-12">
    <%= link_to "Saiba mais", "/infocamara", class: "btn btn-danger" %>
  </div>
  <br>
  <br>
</div>

<div class="section" id="graphs">
  <div class="section-presentation">
    <h3>O QUE É POSSÍVEL FAZER COM ESSES DADOS?</h3>
  </div>
  <div class="container">
    <br>
    <div class="row align-center">
      <div class="col-xs-12 col-sm-4">
        <div class="card align-center margin-left">
          <%= render "votings/index" %>
          <p>Podemos ver a quantidade de votações realizadas na Câmara mensalmente. São consideradas aqui somente votações referentes a um projeto de lei específico.</p>
        </div>
      </div>
      <div class="col-xs-12 col-sm-4">
        <div class="card align-center margin-left">
          <%= column_chart Project.where(ano: 2013..2018).group(:ano).count, thousands: ".", width: "350px", height: "350px", ytitle: "Projetos"%>
          <p>Também conseguimos ver o total de projetos elaborados anualmente pelos vereadores, abrangendo todas as diferentes modalidades (PL, RDS, PR, PLO,...)...</p>
        </div>
      </div>
      <div class="col-xs-12 col-sm-4">
        <div class="card align-center">
          <% status_list = ["Em Tramitação", "Vetado", "Aprovado", "Promulgado", "Encerrado por Ilegalidade", "Retirado pelo autor"] %>
          <%= line_chart status_list.map { |stat|
            {name: stat, data: Project.where(status: stat).group(:ano).count }
          }, height: "350px", thousands: "." %>
          <p>...e desse total, temos a divisão acima quanto à atual situação dos projetos elaborados em cada ano. (Considerando somente PL, PDL, PR e PLO)</p>
        </div>
      </div>
    </div>
    <div class="row align-center">
      <div class="col-xs-12">
        <div class="col-xs-offset-3">
          <div class="info-texto">Para gráficos mais específicos, clique em um dos botões abaixo.</div>
        </div>
      </div>
      <br><br>
      <div class="col-xs-12">
        <span class="col-xs-2 col-xs-offset-4">
          <%= link_to "Vereadores", "/councillors", class: "btn btn-danger", target:"_blank" %>
        </span>
        <span class="col-xs-2">
          <%= link_to "Projetos", "/projects", class: "btn btn-danger", target:"_blank" %>
         </span>
        </span>
      </div>
    </div>
  </div>
</div>

app/views/pages/infocamara.html.erb
<div class="section-c" id="pro-camara">
  <div class="section-presentation">
    <h3>A CÂMARA</h3>
  </div>
</div>
<div class="section-c" id="pro-camara2">
  <div class="section-b">
    <h3>Todas as cidades possuem um grupos de pessoas eleitas para representar o povo</h3>
  </div>
</div>
<div class="wrapper-gray">
  <div class="container">
    <div class="flexbox">
      <div class="flex-item">
        <div class="card-flip">
          <div class="content-flip">
            <div class="front-flip">
              <%= image_tag "represent_icon.png", alt: "represent", width: 200 %>
            </div>
            <div class="back-flip">
              <h4 class="card-title">Os vereadores são os representantes dos cidadãos na cidade</h4>
            </div>
          </div>
        </div>
      </div>
      <div class="flex-item">
        <div class="card-flip">
          <div class="content-flip">
            <div class="front-flip">
              <%= image_tag "care_icon.png", alt: "seats", width: 200 %>
            </div>
            <div class="back-flip">
              <h4 class="card-title">Os vereadores devem respeitar a democracia e buscar o bem-comum para todos, sem qualquer forma de distinção</h4>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="wrapper-gray">
  <div class="container">
    <div class="flexbox">
      <div class="flex-item">
        <div class="card-flip">
          <div class="content-flip">
            <div class="front-flip">
              <%= image_tag "house_icon.png", alt: "house", width: 200 %>
            </div>
            <div class="back-flip">
              <h4 class="card-title">O Palácio Anchieta é o espaço público onde os vereadores se reunem para os debates e votações</h4>
            </div>
          </div>
        </div>
      </div>
      <div class="flex-item">
        <div class="card-flip">
          <div class="content-flip">
            <div class="front-flip">
              <%= image_tag "camara_teste.png", alt: "seats", width: 250 %>
            </div>
            <div class="back-flip">
              <h4 class="card-title">Em São Paulo a Câmara de Vereadores possui 55 cadeiras e 17 partidos políticos</h4>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="section-c" id="pro-camara2">
  <div class="section-b">
    <h3>As principais responsabilidades dos vereadores são</h3>
  </div>
</div>
<div class="wrapper-gray">
  <div class="container">
    <div class="flexbox">
      <div class="flex-item">
        <div class="card-flip">
          <div class="content-flip">
            <div class="front-flip">
             <%= image_tag "law_icon.png", alt: "law", width: 200 %>
            </div>
            <div class="back-flip">
              <h4 class="card-title">
                <p><strong>Leis</strong><p>
                <p>criar, mudam e desfazer as regras que organizam a cidade</p>
              </h4>
            </div>
          </div>
        </div>
      </div>
      <div class="flex-item">
        <div class="card-flip">
          <div class="content-flip">
            <div class="front-flip">
              <%= image_tag "oversee_icon.png", alt: "oversee", width: 200 %>
            </div>
            <div class="back-flip">
              <h4 class="card-title">
                <p><strong>Fiscalizar</strong></p>
                <p>as ações da prefeitura e impedir que quebre Leis ou aja com irresponsabilidade</p>
              </h4>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>


<!-- Os Projetos de Lei (PL) são criados e votados pelos vereadores com a participação do prefeito. É ele que vai confirmar (sancionar) o projeto, transformando ele em lei. O prefeito pode também criar uma lei, mas ela PRECISA ser votadas pelos vereadores -->

app/views/projects/index.html.erb
<div class="projects-wrapper">
  <div class="container">
    <section class="projects-section">
      <div class="section-presentation">
        <h3>PROJETOS</h3>
      </div>
      <div class="row col-xs-12">
        <div class="project-info col-xs-4 col-xs-offset-2">
          <div class="icon">
              <i class="far fa-sticky-note"></i>
            </div>
          <br><br>
          <div class="info-texto">
            <p>As Leis levam diferentes <%= link_to 'nomes', 'http://splegisws.camara.sp.gov.br/ws/ws2.asmx/TiposDeMateria', target:"_blank" %> de acordo com seus objetivos. <br> Ao lado temos uma listagem de algumas delas e o significado de cada sigla.<br>
              Sim, nós concordamos que a maioria dos nomes não é nem um pouco clara. <br>
            A base de dados para gerar os gráficos de quantidade de tipos de projetos foi tirada <%= link_to 'deste arquivo', 'http://splegisws.camara.sp.gov.br/ws/ws2.asmx/ProjetosPorAnoJSON?ano=2018', target:"_blank" %>.</p>
          </div>
        </div>
        <div class="col-xs-4">
          <br>
          <div class="listagem-de-nomes">
            <h4>Lista de nomes</h4>
          </div>
          <div class="scroll-wrapper">
            <%= render 'components/tipos_de_projeto' %>
          </div>
        </div>
      </div> <!-- row  -->
    </section>

    <section class="charts-section">
      <div class="section-presentation">
        <div class="text-center">
          <h3>STATUS E TIPOS DE PROJETOS</h3>
          <p>(Clique nas legendas para filtrar os gráficos)</p>
        </div>
      </div>
      <br>
      <div class="row">
        <div class="row col-xs-5 col-xs-offset-1">
          <div class="chart-box">
            <%= line_chart @status_list.map { |stat|
        {name: stat, data: @projects.where(status: stat).group(:ano).count }
          }, width: "450px", height: "300px", thousands: ".", legend: "bottom" %>
          </div>
          <div class="chart-text">
            <p>Um projeto passa por fases diversas até que seja aprovado. <br> No gráfico acima temos a quantidade de projetos em cada status ao longo dos anos.</p>
          </div>
        </div>
        <div class="row col-xs-5">
          <div class="chart-box">
            <%= line_chart @project_list.map { |project|
          {name: project, data: @projects.where(tipo: project).where(ano: 2013..2018).group(:ano).count }
            }, width: "450px", height: "300px", thousands: ".", legend: "bottom", discrete: "true" %>
          </div>
          <div class="chart-text">
            <p>No gráfico acima listamos a quantidade de projetos pelos tipos que aparecem em maior quantidade na base de dados, sendo eles Projeto de Lei, Projeto de Decreto Legislativo, Requerimento, Indicação e Substitutivo.</p>
          </div>
        </div>
      </div>
    </section>
    <section>
      <div class="section-presentation">
        <div class="row">
          <div class="text-center">
            <h3>QUANTIDADE DE PROJETOS POR TIPO</h3>
            <p>(Mandato atual)</p>
          </div>
        </div>
      </div>
      <br>
      <div class="row">
        <div class="col-xs-12">
          <div class="col-xs-4 col-xs-offset-1">
            <h4>2018</h4>
            <%= column_chart Project.where(ano: 2018).group(:tipo).count, thousands: ".", xtitle: "Tipo de matéria", ytitle: "Quantidade", width: "450px" %>
          </div>
          <div class="col-xs-1"></div>
          <div class="col-xs-4">
            <h4>2017</h4>
            <%= column_chart Project.where(ano: 2017).group(:tipo).count, thousands: ".", xtitle: "Tipo de matéria", ytitle: "Quantidade", width: "450px"  %>
          </div>
        </div>
      </div>
    </section>
  </div>
</div>

app/views/votings/_index.html.erb
<%= column_chart Voting.grouped_by_year, thousands: ".", ytitle: "Votações", height: "350px" %>